name: Check

on:
  pull_request:

  push:
    branches:
      - main # Check branch after merge

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-code-style:
    name: Code Style # scalafmt, javafmt, headerCheck
    uses: playframework/.github/.github/workflows/cmd.yml@v3
    with:
      cmd: sbt validateCode

  tests:
    name: Tests
    uses: playframework/.github/.github/workflows/cmd.yml@v3
    with:
      java: 17, 11
      scala: 2.12.19
      add-dimensions: >-
        {
          "sbt": [ "1.9.0" ]
        }
      cmd: >-
        sbt "
          set scriptedSbt := \"$MATRIX_SBT\";
          set scriptedLaunchOpts += \"-Dscala.version=$MATRIX_SCALA\";
          show scriptedSbt;
          show scriptedLaunchOpts;
          scripted;
        "  

  finish:
    name: Finish
    if: github.event_name == 'pull_request'
    needs: # Should be last
      - "tests"
    uses: playframework/.github/.github/workflows/rtm.yml@v3
